### ISSUE TITLE
Two title containers

### ISSUE THREAD

**Issue by alboss-cascadia** [ecortes-web/ecortes-web.github.io#1]
https://ecortes-web.github.io/Personal%20Website/support.html has got two title containers. Only one is legally allowed by the official HTML specs.

**Comment by ecortes-web** [comment]
my current code is under the "finished-website" repo (https://github.com/ecortes-web/ecortes-web.github.io/blob/master/finished-website/support.html) and in the support.html their are no double title containers. I apologize for the messy folders i tried to delete the "Personal Website" Folder due to the caps and spaces it has but haven't been able to find out how to delete them.

**Comment by alboss-cascadia** [comment]
I was looking in the wrong place; sorry about that!
